// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxtptAp8egEZ7Bke5YxnuIGkqyUJ0Ge58',
    appId: '1:965744496199:web:79c03bc4621493009fab62',
    messagingSenderId: '965744496199',
    projectId: 'smarket-8aa30',
    authDomain: 'smarket-8aa30.firebaseapp.com',
    storageBucket: 'smarket-8aa30.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd9A6u1VJj7NQKTCNS9tyIsfdSCB-_bTU',
    appId: '1:965744496199:android:7d5cf0e1accd324b9fab62',
    messagingSenderId: '965744496199',
    projectId: 'smarket-8aa30',
    storageBucket: 'smarket-8aa30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChXvnShTIBFq7l9-x7Pf1Mz-gW4MF_fdY',
    appId: '1:965744496199:ios:bdad69e10a56ef0a9fab62',
    messagingSenderId: '965744496199',
    projectId: 'smarket-8aa30',
    storageBucket: 'smarket-8aa30.appspot.com',
    iosClientId: '965744496199-g0ufgvi7i5nvo3itm1229emsl3ld8lic.apps.googleusercontent.com',
    iosBundleId: 'com.example.pimSmarket',
  );
}
